# 集成测试配置文件
# 专门用于公益项目管理系统的集成测试

spring:
  profiles:
    active: integration
    
  # 数据库配置 - 使用测试数据库
  datasource:
    url: jdbc:mysql://localhost:3306/yxrobot_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # 缓存配置 - 使用内存缓存进行测试
  cache:
    type: simple  # 使用简单的内存缓存

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: none  # 不自动创建表，使用现有的测试数据
    show-sql: false   # 集成测试时不显示SQL，减少日志噪音
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yxrobot.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial

# 日志配置 - 集成测试时使用较低的日志级别
logging:
  level:
    com.yxrobot: INFO
    org.springframework: WARN
    org.mybatis: WARN
    org.hibernate: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 缓存配置 - 使用内存缓存
cache:
  memory:
    default-expiration: 300  # 5分钟默认过期时间
    charity:
      stats-expiration: 600   # 统计数据缓存10分钟
      chart-expiration: 1800  # 图表数据缓存30分钟
      list-expiration: 300    # 列表数据缓存5分钟

# 测试专用配置
test:
  # 数据初始化配置
  data:
    init-charity-data: true
    cleanup-after-test: true
    
  # 性能测试配置
  performance:
    max-response-time: 2000  # 最大响应时间2秒
    concurrent-threads: 10   # 并发测试线程数
    requests-per-thread: 5   # 每个线程的请求数
    
  # 缓存测试配置
  cache:
    test-expiration: 1  # 缓存过期测试时间1秒
    
# 应用配置
app:
  name: YXRobot-Integration-Test
  version: 1.0.0-TEST
  
# 文件上传配置（测试环境）
file:
  upload:
    path: ./test-uploads/
    max-size: 10MB
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx

# 安全配置（测试环境放宽限制）
security:
  jwt:
    secret: test-secret-key-for-integration-testing-only
    expiration: 3600000  # 1小时
    
# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized