# 开发环境配置
server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    basedir: ./target/tomcat-dev

# Spring Boot 开发工具配置
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
      exclude: static/**,public/**,logs/**,target/**
      poll-interval: 1000
      quiet-period: 400
    livereload:
      enabled: true
      port: 35729
    add-properties: true
  
  # 静态资源配置
  web:
    resources:
      static-locations: 
        - classpath:/static/
        - file:src/frontend/dist/
      cache:
        period: 0
  
  # 数据源配置（开发环境 - 使用远程MySQL数据库）
  datasource:
    url: jdbc:mysql://yun.finiot.cn:3306/YXRobot?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: YXRobot
    password: 2200548qq
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    # 连接池配置
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: YXRobotDevHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1



# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yxrobot.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: warning
    default-executor-type: simple
    default-statement-timeout: 25
    default-fetch-size: 100
    safe-row-bounds-enabled: false
    local-cache-scope: session
    jdbc-type-for-null: other
    lazy-load-trigger-methods: equals,clone,hashCode,toString
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.yxrobot: DEBUG
    org.springframework.web: DEBUG

    com.yxrobot.mapper: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/yxrobot-dev.log
    max-size: 10MB
    max-history: 30

# 开发环境特殊配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always