# 简化配置，用于快速启动
server:
  port: 8081

spring:
  
  # H2数据库配置
  datasource:
    url: jdbc:h2:mem:yxrobot;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  # 初始化数据
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true
    
  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  
  # SQL初始化配置
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true

  # 使用内存缓存
  cache:
    type: simple

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yxrobot.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# 日志配置
logging:
  level:
    com.yxrobot: INFO
    org.springframework: WARN
    org.apache.ibatis: WARN